//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_System_2020.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Ticket
    {
        [Required]
        public int TicketID { get; set; }
        [Required]
        public string ProjetName { get; set; }
        [Required]
        public string DepartmentName { get; set; }
        [Required]
        public string RequestName { get; set; }
        [Required]
        public string ProblemDescription { get; set; }
        public System.DateTime TimeRequested { get; set; }
    }
}
